import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/layout/Header";

const gotham = localFont({
  src: [
    { path: "../../public/fonts/Gotham-Light.woff2", weight: "300" },
    { path: "../../public/fonts/Gotham-Book.woff2", weight: "400" },
    { path: "../../public/fonts/Gotham-Medium.woff2", weight: "500" },
    { path: "../../public/fonts/Gotham-Bold.woff2", weight: "700" },
  ],
  variable: "--font-gotham",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${gotham.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-white text-black">
        <Header />
        {children}
      </body>
    </html>
  );
}
